import { DailyParticipant, DailyStreamingOptions } from "@daily-co/daily-js";

export function getVCSConfig(
  activeParticipant?: DailyParticipant
): DailyStreamingOptions<"recording"> {
  console.log("HEY ACTIVE:", activeParticipant);
  //   NOTE: Stupid mode is not updating
  const mode = activeParticipant ? "split" : "single";
  console.log("MODE:", mode);

  //   Note2: If we always do split, we will always show at least 1 participant even if we set the numChiclets to 0...

  return {
    instanceId: "00000000-0000-4000-8000-000000000000", // optional: default value
    width: 720,
    height: 1280,
    videoBitrate: 5000,
    audioBitrate: 320,
    fps: 25,
    layout: {
      preset: "custom",
      composition_id: "daily:baseline",
      composition_params: {
        mode: activeParticipant ? "split" : "single",
        showTextOverlay: false,
        showImageOverlay: true,
        showTitleSlate: false,
        enableAutoOpeningSlate: false,
        // 'videoSettings.preferredParticipantIds': remoteParticipantIds.slice(0, 4).join(','), // BTW I have no clue if this will work, I guess we'll find out
        "videoSettings.maxCamStreams": 25,
        "videoSettings.preferScreenshare": true,
        "videoSettings.omitPaused": false,
        "videoSettings.omitAudioOnly": false,
        "videoSettings.omitExtraScreenshares": true,
        "videoSettings.showParticipantLabels": false,
        "videoSettings.roundedCorners": false,
        "videoSettings.cornerRadius_gu": 1.2,
        "videoSettings.scaleMode": "fill",
        "videoSettings.scaleModeForScreenshare": "fit",
        "videoSettings.placeholder.bgColor": "rgb(0, 50, 80)",
        "videoSettings.highlight.color": "rgb(255, 255, 255)",
        "videoSettings.highlight.stroke_gu": 0.3,
        "videoSettings.split.margin_gu": 0,
        "videoSettings.split.direction": "auto-by-viewport",
        "videoSettings.grid.useDominantForSharing": false,
        "videoSettings.grid.itemInterval_gu": -1,
        "videoSettings.grid.outerPadding_gu": -1,
        "videoSettings.grid.highlightDominant": true,
        "videoSettings.grid.preserveAspectRatio": true,
        "videoSettings.dominant.position": "top",
        "videoSettings.dominant.splitPos": activeParticipant ? 0.5 : 1,
        "videoSettings.dominant.numChiclets": activeParticipant ? 1 : 0,
        "videoSettings.dominant.followDomFlag": false,
        "videoSettings.dominant.itemInterval_gu": 0,
        "videoSettings.dominant.outerPadding_gu": 0,
        "videoSettings.dominant.splitMargin_gu": 0,
        "videoSettings.dominant.sharpCornersOnMain": true,
        // "videoSettings.pip.position": "top-right",
        // "videoSettings.pip.aspectRatio": 1,
        // "videoSettings.pip.height_gu": 1,
        // "videoSettings.pip.margin_gu": 1.5,
        // "videoSettings.pip.followDomFlag": false,
        // "videoSettings.pip.sharpCornersOnMain": true,
        "videoSettings.labels.fontFamily": "Roboto",
        "videoSettings.labels.fontWeight": "400",
        "videoSettings.labels.fontSize_pct": 100,
        "videoSettings.labels.offset_x_gu": 0,
        "videoSettings.labels.offset_y_gu": 10,
        "videoSettings.labels.color": "white",
        "videoSettings.labels.strokeColor": "rgba(0, 0, 0, 0.9)",
        "videoSettings.margin.left_gu": 0,
        "videoSettings.margin.right_gu": 0,
        "videoSettings.margin.top_gu": 0,
        "videoSettings.margin.bottom_gu": 0,
        // 'text.content': roomName,
        "text.align_horizontal": "left",
        "text.align_vertical": "top",
        "text.offset_x_gu": 0.5,
        "text.offset_y_gu": 2.2,
        "text.rotation_deg": 0,
        "text.fontFamily": "Roboto",
        "text.fontWeight": "300",
        "text.fontSize_gu": 1.6,
        "text.color": "white",
        "text.strokeColor": "black",
        // "image.assetName": "tempLogo",
        // "image.position": "bottom-right",
        // "image.fullScreen": true,
        // "image.aspectRatio": 1.478,
        // "image.height_gu": 3,
        // "image.margin_gu": 0,
        // "image.opacity": 1,
        // "image.enableFade": true,
        "webFrame.keyPress.keyName": "ArrowRight",
        "webFrame.keyPress.key": 0,
        "toast.key": 0,
        "toast.text": "Hello world",
        "toast.duration_secs": 4,
        "toast.numTextLines": 2,
        "toast.showIcon": true,
        "toast.color": "rgba(15, 50, 110, 0.6)",
        "toast.strokeColor": "rgba(0, 0, 30, 0.44)",
        "toast.text.color": "white",
        "toast.text.fontFamily": "Roboto",
        "toast.text.fontWeight": "500",
        "toast.text.fontSize_pct": 100,
        "openingSlate.duration_secs": 4,
        "openingSlate.title": "Welcome",
        "openingSlate.bgColor": "rgba(0, 0, 0, 1)",
        "openingSlate.textColor": "rgba(255, 255, 255, 1)",
        "openingSlate.fontFamily": "Bitter",
        "openingSlate.fontWeight": "500",
        "openingSlate.fontSize_gu": 2.5,
        "openingSlate.subtitle.fontSize_pct": 75,
        "openingSlate.subtitle.fontWeight": "400",
        "titleSlate.title": "",
        "titleSlate.subtitle": "",
        "titleSlate.bgColor": "rgba(0, 0, 0, 1)",
        "titleSlate.textColor": "rgba(255, 255, 255, 1)",
        "titleSlate.fontFamily": "Bitter",
        "titleSlate.fontWeight": "500",
        "titleSlate.fontSize_gu": 2.5,
        "titleSlate.subtitle.fontSize_pct": 75,
        "titleSlate.subtitle.fontWeight": "400",
      },
      //   session_assets: {
      //     "images/logo":
      //       "https://www.learnontil.com/_next/image?url=%2FtilLogoTransparentAlternative.png&w=256&q=75",
      //     "images/tempLogo":
      //       "https://cdn.glitch.global/972392e4-cc27-4f74-b954-16c9390bc628/VCS%20Position%20Export.png?v=1682990172259",
      //   },
    },
  };
}
